### ISSUE TITLE
老铁，PickerView显示出来后，标题似乎没有居中啊，偏了大概有20像素

### ISSUE THREAD

**Issue by Whereeee** [Coder-Star/CSPickerView#1]
设备iPhone 12 mini

**Comment by Coder-Star** [comment]
具体是哪一个pickview，贴个链接或者路径吧

**Comment by Whereeee** [comment]
我试了showSingleColPicker，showMultipleAssociatedColsPicker都有便宜，我上传个iPhone 14 Pro

**Comment by Whereeee** [comment]
你好，就是用 PickerViewManager.showSingleColPicker和PickerViewManager.showMultipleAssociatedColsPicker 弹出来的选择器的title文字不居中，我用模拟器iPhone 14 Pro测试，发现标题向右偏了大约88像素，我github用的少，不太熟练，前面点错了，不好意思

**Comment by Whereeee** [comment]
有没有技术群啊，能加你的群不

**Comment by Whereeee** [comment]
我还尝试了使用空格占位，发现也不行，应该是x坐标起点靠右了

**Comment by Coder-Star** [comment]
你加我微信，微信号： Star-Coder

**Comment by Whereeee** [comment]
好的，多谢
